language: cpp
compiler:
  - gcc
before_install:
 - yes | sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq devscripts equivs
 - sudo mk-build-deps --install debian/control
script: debuild -i -us -uc -b
branches:
  only:
    - master
notifications:
  recipients:
    - ville.ranki@iki.fi
  email:
    on_success: change
    on_failure: always

