language: cpp
compiler:
  - gcc
before_install:
 - yes | sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq debhelper qtbase5-dev qt5-default cdbs devscripts qtchooser libqt5webkit5-dev qtdeclarative5-dev
script: debuild
branches:
  only:
    - master
notifications:
  recipients:
    - ville.ranki@iki.fi
  email:
    on_success: change
    on_failure: always

