language: cpp
compiler:
  - gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq debhelper qtbase5-dev qt5-default cdbs devscripts
script: dpkg-buildpackage -rfakeroot -b
branches:
  only:
    - master
notifications:
  recipients:
    - ville.ranki@iki.fi
  email:
    on_success: change
    on_failure: always

